<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Botonera</title>
</head>
<body>
<header>
<div class="logo">
            <div>
                <img class="intro-img" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXv2xVzLvFb9HcBhj7y91VX9vz1Y-lJLhgLqCDwPyE-A&s" alt="icono temporal">
            </div>
            <div class="intro">
                <h1 class="intro-txt">Mercado</h1>
                <h1 class="intro-txt">Mitico</h1>
            </div>
        </div>
        <form action="Buscar" method=POST class="my-4">
        <input class="bloque-buscador" type="text" name="buscador" placeholder="Search">
        <button type="submit">Buscar</button>
</form>
        <div class="slogan">
            <p class="intro-txt">"objetos fantasticos"</p>
          <?php 
           if(isset($_SESSION['user_mail'])){
            ?><a href="logout"> logout </a> <?php
           }else {
            ?><a href='entrar'>Login o Registrarse</a><?php
           } 
          ?>
        </div>
    </header>
    <nav class="btn_menu"><a><b> Categorias</b></a></nav>
    <nav class="menu">
        <ul class="navigation">
        <?php foreach($categorias as $categoria){ ?>
       <li class="botonera"><a href="categoria/<?=$categoria->id?>"><?= $categoria->Categorias ?></a></li>  <?php
     } ?>
     <li class="botonera"><a href="home">Todas</a></li>
        </ul>
    </nav>
    </body>