
<header>
<div class="logo">
            <div>
                <img class="intro-img" src="https://icons-for-free.com/iconfiles/png/512/hat+spooky+witch+wizard+icon-1320195189254517755.png" alt="icono temporal">
            </div>
            <div class="intro">
                <h1 class="intro-txt">Mercado</h1>
                <h1 class="intro-txt">Mitico</h1>
            </div>
        </div>
        <input class="bloque-buscador" type="search" name="buscador" placeholder="Search">
        <div class="slogan">
            <p class="intro-txt">"objetos fantasticos"</p>
          <?php 
           if(isset($_SESSION['user_mail'])){
            ?><a href='/tpo_web2/logout'> logout </a> <?php
           }else {
            ?><a href='/tpo_web2/entrar'>Login o Registrarse</a><?php
           } 
          ?>
        </div>
    </header>
    <nav class="btn_menu"><a><b> Categorias</b></a></nav>
    <nav class="menu">
        <ul class="navigation">
        <?php foreach($categorias as $categoria){ ?>
       <li class="botonera"><a href="http://localhost/tpo_web2/categoria/<?=$categoria->id?>"><?= $categoria->Categorias ?></a></li>  <?php
     } ?>
     <li class="botonera"><a href="home">Todas</a></li>
        </ul>
    </nav>