<link rel="stylesheet" href="./css/style.css">
<div class="des-producto">
    <div>
        <div class="des-img">
            <h1><?php $imagen ?></h1>
        </div>
        <div>
            <h1><?php $Producto ?></h1>
            <h1><?php $Precio
            ?></h1>
        </div>
        
    </div>
    <div>
            <h2>Descripcion del Producto: </h2>
            <p>blablabla</p>
    </div>
</div>

