<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Descripcion producto</title>
</head>
<body>
<div class="des-producto">
    <div>
        <div class="des-img">
        <img class="img-desc"  src='<?= $producto->Imagen ?>' >
        </div>
        <div>
            <h1><?= $producto->Producto ?></h1>
            <h1><?= $producto->Precio ?>$</h1>
        </div>
        
    </div>
    <div>
            <h2>Descripcion del Producto: </h2>
            <p><?= $producto->Descripcion ?></p>
            <h2>Categoria del Producto: </h2>
            <p><?= $categorias->Categorias ?></p>
    </div>
</div>

<a href=<?= BASE_URL ?> >Ir al sitio principal</a> 


</body>