

<div class="des-producto">
    <div>
        <div class="des-img">
        <img class="img-desc"  src='<?= $producto->Imagen ?>' >
        </div>
        <div>
            <h1><?= $producto->Producto ?></h1>
            <h1><?= $producto->Precio ?>$</h1>
        </div>
        
    </div>
    <div>
            <h2>Descripcion del Producto: </h2>
            <p><?= $producto->Descripcion ?></p>
    </div>
</div>

<a href=<?= BASE_URL ?> >Ir al sitio principal</a> 


