<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Footer</title>
</head>
<body>
<footer>
<?php if(isset($_SESSION['user_permisos'])){
    if($_SESSION['user_permisos']==1){ ?>
        <a href="añadiroquitar_producto">Agregar Productos</a>
    <?php } 
}?>

        <div class="copyright">&#169; 2023 Mercado Mitico; By Ignacio Margni & Matias Morcillo</div>

    
        
    </footer>
</body>