<h1>Registrar un producto</h1>
<div class="form-box">
<form required action="http://localhost/tpo_web2/modificar_producto//<?=$id?>" method="POST" class="my-4">
    <label>Producto</label>
    <input name="Producto" type="text">
    <label>Link de la imagen</label>
    <input name="Imagen" type="text">
    <label>Precio</label>
    <input name="Precio" type="text"></input>
    <select name="Categoria">
        
        <?php foreach($categorias as $categoria){ ?>
 
         <option value=<?=$categoria->Categorias?>> <?=$categoria->Categorias?> </option>

        <?php } ?> 

    </select>
    <button type="submit">Guardar</button>
</form>
</div>