<article class="seccion-todo">
<?php
foreach($Productos as $Producto): ?>

<div class="producto">
<img class="imagen-prod"  src='<?= $Producto->Imagen ?>' >
<h1> <?= $Producto->Producto ?> </h1>
<p><b>Precio</b></p>
<p><?= $Producto->Precio ?>$</p>
<a href='/tpo_web2/quitar_producto/<?=$Producto->id?>'>Suprimir</a>
<a href='/tpo_web2/form_modificar/<?=$Producto->id?>'>Modificar</a>
</div>

<?php endforeach ?>                  
</article>
         