<h1>Registrar un producto</h1>
<div class="form-box">
<form required action="insertar_producto" method="POST" class="my-4">
    <label>Producto</label>
    <input name="Producto" type="text">
    <label>Link de la imagen</label>
    <input name="Imagen" type="text">
    <label>Precio</label>
    <input name="Precio" type="text"></input>
    <button type="submit">Guardar</button>
</form>
<form>
    <label>Categorias</label>
    <input name="categorias">
    <button type="submit">Guardar</button>
</form>
</div>