<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Verificar usuario</title>
</head>
<body>
<h1>Verifique sus credenciales</h1>
<div class="form-box">
<form required action="verificar_usuario2" method="POST" >
    <label>Mail</label>
    <input name="Mail" type="text">
    <label>Contraseña</label>
    <input name="Contraseña" type="text"></input>
    <button type="submit">Ingresar</button>
</form>
<div>
</body>
